pki:
  ca: /tmp/nebula/ca.crt
  cert: /tmp/nebula/operator.crt
  key: /tmp/nebula/operator.key

static_host_map:
  "192.168.100.1": ["LIGHTHOUSE_IP_ADDRESS:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.100.1"

listen:
  host: 0.0.0.0
  port: 4242

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: icmp
      host: any

    - port: any
      proto: any
      group: team-server

  inbound:
    - port: any
      proto: icmp
      host: any

    - port: any
      proto: any
      group: team-server
